### ISSUE TITLE
Getting an error when pulling from the cloud source

### ISSUE THREAD

**Issue by zizther** [weareferal/craft-sync#14]
The error I am getting is `Calling unknown method: weareferal\sync\services\providers\S3Service::actionPullDatabase()`

I am able to push a database, but when I pull on staging or local this error shows, I have enabled the Use Craft Queue setting.

I am using Craft 3.4.4.1 and env-sync 1.0.13

**Comment by timmyomahony** [comment]
Thanks @zizther that should be fixed now in the latest release.

**Comment by zizther** [comment]
@timmyomahony Thanks for looking at that, there is another issue which now occurs when doing the same with with version 1.0.14

`Undefined index: extension`
`Undefined index: extension in /.../vendor/weareferal/env-sync/src/services/providers/S3Provider.php:95`

**Comment by timmyomahony** [comment]
Hmmm, I'll have to have a closer look

**Comment by timmyomahony** [comment]
Hopefully this should be fixed in v1.1.0

**Comment by kylerits** [comment]
I am still seeing this issue when trying to pull a db from S3. I am using Craft CMS v 3.4.9 and Env Sync v 1.1.1. I am getting an error of "Undefined index: extension"

**Comment by kylerits** [comment]
Pushing from local is working just fine. I am also able to make and push db backups from local. It is only pulling that seems to be having an issue.

**Comment by timmyomahony** [comment]
This sounds like a different issues to this one. I'll check out the separate issues you posted. I haven't seen that error before.
